// C4D-DialogResource
DIALOG ID_RAMPLAYER
{
  NAME IDS_IDD_DIALOG; FIT_V; SCALE_V; FIT_H; SCALE_H; 
  
  GROUP IDC_TOPMOST
  {
    NAME IDS_STATIC; FIT_V; SCALE_V; FIT_H; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC10; ALIGN_TOP; FIT_H; SCALE_H; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 5, -2, 0, -4; 
      COLUMNS 1;
      
      STATICTEXT RP_PATH { NAME IDS_STATIC7; CENTER_V; FIT_H; SCALE_H; SIZE 0, 15; }
    }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC8; ALIGN_TOP; FIT_H; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      GROUP RP_G_TIMELINE
      {
        ALIGN_TOP; FIT_H; SCALE_H; 
        BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 4, 4, 4, 4; 
        ROWS 1;
        SPACE 4, 4;
        
        BUTTON RP_TOSTART { NAME IDS_BUTTON; ALIGN_TOP; CENTER_H; }
        BUTTON RP_ONEBACK { NAME IDS_BUTTON1; ALIGN_TOP; CENTER_H; }
        BUTTON RP_REWIND { NAME IDS_BUTTON4; ALIGN_TOP; CENTER_H; }
        BUTTON RP_STOP { NAME IDS_BUTTON2; ALIGN_TOP; CENTER_H; }
        BUTTON RP_PLAY { NAME IDS_BUTTON3; ALIGN_TOP; CENTER_H; }
        BUTTON RP_ONEFOR { NAME IDS_BUTTON5; ALIGN_TOP; CENTER_H; }
        BUTTON RP_TOEND { NAME IDS_BUTTON6; ALIGN_TOP; CENTER_H; }
        SEPARATOR { SCALE_V; }
        SEPARATOR { SCALE_V; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC12; CENTER_V; ALIGN_LEFT; }
        EDITNUMBERARROWS RP_FPS
        { CENTER_V; CENTER_H; SIZE 30, 0; }
        STATICTEXT IDC_STATIC { NAME IDS_STATIC13; CENTER_V; CENTER_H; }
        GROUP IDC_STATIC
        {
          CENTER_V; ALIGN_LEFT; 
          BORDERSTYLE BORDER_IN; BORDERSIZE 4, 1, 4, 1; 
          COLUMNS 1;
          
          STATICTEXT RP_SIZE { NAME IDS_STATIC14; CENTER_V; ALIGN_LEFT; }
        }
      }
    }
    GROUP RP_G_SETTINGS
    {
      ALIGN_TOP; FIT_H; SCALE_H; 
      BORDERSTYLE BORDER_IN; BORDERSIZE 4, 4, 4, 4; 
      ROWS 1;
      SPACE 0, 0;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; CENTER_H; }
      EDITSLIDER RP_FRAME
      { CENTER_V; FIT_H; SCALE_H; SIZE 70, 0; }
    }
    GROUP RP_G_DISPLAY
    {
      FIT_V; SCALE_V; FIT_H; SCALE_H; 
      BORDERSTYLE BORDER_GROUP_OUT; BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      USERAREA RP_MOVIE { FIT_V; SCALE_V; FIT_H; SCALE_H; SIZE 100, 100; }
    }
  }
}
